// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my profile",
  description: "Get the signed-in user's K Cup Cafe profile (display name, avatar, email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const profile = {
      email: ctx.getUserEmail() ?? null,
      display_name: data?.display_name ?? null,
      avatar_url: data?.avatar_url ?? null,
      created_at: data?.created_at ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/update-display-name.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_display_name_default = defineTool2({
  name: "update_display_name",
  title: "Update display name",
  description: "Update the signed-in user's display name on their K Cup Cafe profile.",
  inputSchema: {
    display_name: z.string().trim().min(1).max(80).describe("New display name to set.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ display_name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("profiles").upsert({ user_id: userId, display_name }, { onConflict: "user_id" }).select("display_name").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Display name updated to "${data?.display_name ?? display_name}".` }],
      structuredContent: { display_name: data?.display_name ?? display_name }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fandlesupmxmcxadklay";
var mcp_default = defineMcp({
  name: "k-cup-cafe-mcp",
  title: "K Cup Cafe",
  version: "0.1.0",
  instructions: "Tools for K Cup Cafe. Use `get_profile` to read the signed-in user's profile and `update_display_name` to change their display name.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, update_display_name_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
